"""
InsightForge AI — Professional PDF Report Generator
Creates comprehensive, multi-section reports with charts, statistical tables,
correlation analysis, data quality assessment, and AI insights.
"""

import os
import io
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas
from loguru import logger


# Modern slate-indigo color palette
PRIMARY = "#1e293b"    # slate-800
SECONDARY = "#475569"  # slate-600
ACCENT = "#6366f1"     # indigo-500
DARK = "#0f172a"       # slate-900
MUTED = "#64748b"      # slate-500
LIGHT_BG = "#f8fafc"   # slate-50
BORDER = "#cbd5e1"     # slate-300
SUCCESS = "#0f766e"    # teal-700
WARNING = "#d97706"    # amber-600
DANGER = "#e11d48"     # rose-600


class NumberedCanvas(canvas.Canvas):
    """
    A ReportLab canvas that performs page number calculation via a two-pass save,
    and draws beautiful professional headers/footers on all pages except the cover.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        # A4 Page size is 595.27 x 841.89 points
        width, height = 595.27, 841.89
        left_margin = 22 * mm
        right_margin = width - (22 * mm)

        if self._pageNumber == 1:
            # First page is the cover page
            # Draw a premium modern accent background header block on the canvas
            self.saveState()
            self.setFillColor(colors.HexColor(PRIMARY))
            self.rect(0, height - 140, width, 140, fill=1, stroke=0)
            
            # Subtle accent line at the bottom of the band
            self.setFillColor(colors.HexColor(ACCENT))
            self.rect(0, height - 146, width, 6, fill=1, stroke=0)
            
            # Draw professional top-left title text
            self.setFont("Helvetica-Bold", 12)
            self.setFillColor(colors.white)
            self.drawString(left_margin, height - 80, "INSIGHTFORGE AI")
            self.restoreState()
            return

        # Subsequent pages
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor(SECONDARY))

        # 1. Running Header
        self.drawString(left_margin, height - 42, "InsightForge AI — Comprehensive Data Analysis Report")
        self.setStrokeColor(colors.HexColor(BORDER))
        self.setLineWidth(0.5)
        self.line(left_margin, height - 48, right_margin, height - 48)

        # 2. Running Footer
        self.line(left_margin, 52, right_margin, 52)
        self.drawString(left_margin, 38, "Generated by InsightForge AI")
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(right_margin, 38, page_str)
        self.restoreState()



class ReportGenerator:
    """Generates comprehensive PDF reports from analysis results."""

    def __init__(self, output_dir: str = "data/reports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def _add_custom_styles(self):
        """Add custom paragraph styles for branding."""
        self.styles.add(ParagraphStyle(
            name="BrandTitle", parent=self.styles["Title"],
            fontSize=26, textColor=colors.HexColor(PRIMARY),
            spaceAfter=8, fontName="Helvetica-Bold",
        ))
        self.styles.add(ParagraphStyle(
            name="SubTitle", parent=self.styles["Normal"],
            fontSize=12, textColor=colors.HexColor(MUTED),
            spaceAfter=20, fontName="Helvetica",
        ))
        self.styles.add(ParagraphStyle(
            name="SectionTitle", parent=self.styles["Heading2"],
            fontSize=12, textColor=colors.HexColor(PRIMARY),
            spaceBefore=0, spaceAfter=0, fontName="Helvetica-Bold",
        ))
        self.styles.add(ParagraphStyle(
            name="SubSection", parent=self.styles["Heading3"],
            fontSize=10.5, textColor=colors.HexColor(PRIMARY),
            spaceBefore=10, spaceAfter=4, fontName="Helvetica-Bold",
        ))
        self.styles.add(ParagraphStyle(
            name="BodyCustom", parent=self.styles["Normal"],
            fontSize=9, leading=14, textColor=colors.HexColor(SECONDARY),
        ))
        self.styles.add(ParagraphStyle(
            name="MetricLabel", parent=self.styles["Normal"],
            fontSize=8, textColor=colors.HexColor(MUTED),
            alignment=TA_CENTER,
        ))
        self.styles.add(ParagraphStyle(
            name="MetricValue", parent=self.styles["Normal"],
            fontSize=16, textColor=colors.HexColor(DARK),
            alignment=TA_CENTER, fontName="Helvetica-Bold",
        ))

    def create_section_header(self, title_text: str) -> Table:
        """Create a section header with a beautiful left accent bar."""
        p = Paragraph(title_text, self.styles["SectionTitle"])
        t = Table([[p]], colWidths=[470])
        t.setStyle(TableStyle([
            ("LINELEFT", (0, 0), (0, -1), 3.5, colors.HexColor(ACCENT)),
            ("LEFTPADDING", (0, 0), (0, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
        ]))
        return t

    def get_modern_table_style(self, header_bg=PRIMARY):
        """Return a modern TableStyle without vertical grids."""
        return TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(header_bg)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("LINEBELOW", (0, 0), (-1, 0), 1.5, colors.HexColor(PRIMARY)),
            ("LINEBELOW", (0, 1), (-1, -1), 0.5, colors.HexColor(BORDER)),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor(LIGHT_BG)]),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ])


    def generate_report(
        self,
        dataset_name: str,
        summary_stats: Dict[str, Any],
        insights: str,
        chart_insights: Optional[Dict[str, str]] = None,
        ml_results: Optional[Dict] = None,
        anomaly_results: Optional[Dict] = None,
        correlation: Optional[Dict] = None,
    ) -> str:
        """Generate a comprehensive PDF report and return the filename."""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"insightforge_report_{timestamp}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        doc = SimpleDocTemplate(
            filepath, pagesize=A4,
            leftMargin=22 * mm, rightMargin=22 * mm,
            topMargin=22 * mm, bottomMargin=22 * mm,
        )

        elements = []
        shape = summary_stats.get("shape", {})
        num_summary = summary_stats.get("numeric_summary", {})
        cat_summary = summary_stats.get("categorical_summary", {})
        classification = summary_stats.get("column_classification", {})

        # ── 1. TITLE PAGE ─────────────────────────────────────
        elements.append(Spacer(1, 80))  # Extra space below the top cover band
        elements.append(Paragraph("⚡ InsightForge AI", self.styles["BrandTitle"]))
        elements.append(Paragraph("Comprehensive Data Analysis Report", self.styles["SubTitle"]))
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor(PRIMARY)))
        elements.append(Spacer(1, 25))

        # Dataset info box
        info_data = [
            ["Dataset File", dataset_name],
            ["Generated At", datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")],
            ["Total Records", f"{shape.get('rows', 'N/A'):,}"],
            ["Feature Count", str(shape.get('columns', 'N/A'))],
        ]
        info_table = Table(info_data, colWidths=[110, 340], hAlign="LEFT")
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(LIGHT_BG)),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(BORDER)),
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor(DARK)),
            ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor(SECONDARY)),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 15))

        # Classification info
        if classification:
            notes = []
            if classification.get("id_columns"):
                notes.append(f"ID columns (excluded from analysis): {', '.join(classification['id_columns'])}")
            if classification.get("datetime_columns"):
                notes.append(f"Date/time columns detected: {', '.join(classification['datetime_columns'])}")
            for note in notes:
                elements.append(Paragraph(f"ℹ️ {note}", self.styles["BodyCustom"]))
            if notes:
                elements.append(Spacer(1, 10))

        elements.append(PageBreak())

        # ── EXECUTIVE SUMMARY ─────────────────────────────────
        elements.append(self.create_section_header("📋 Executive Summary"))
        elements.append(Spacer(1, 8))
        rows = shape.get('rows', 0)
        cols_count = shape.get('columns', 0)
        num_count = len(num_summary)
        cat_count = len(cat_summary)
        exec_text = (
            f"This report presents a comprehensive analysis of the <b>{dataset_name}</b> dataset "
            f"containing <b>{rows:,}</b> records across <b>{cols_count}</b> features "
            f"({num_count} numeric, {cat_count} categorical). "
            f"The analysis pipeline includes data quality assessment, exploratory data analysis (EDA), "
            f"statistical testing, correlation analysis, and machine learning modeling. "
            f"Key findings and actionable recommendations are provided for decision-makers."
        )
        elements.append(Paragraph(exec_text, self.styles["BodyCustom"]))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            "<b>Problem:</b> Extract actionable insights from structured data to support evidence-based decision-making.",
            self.styles["BodyCustom"]))
        elements.append(Paragraph(
            "<b>Approach:</b> Data was sourced, cleaned via Python ETL pipeline, analysed with statistical and ML methods, and visualised for stakeholder consumption.",
            self.styles["BodyCustom"]))
        elements.append(Spacer(1, 10))

        # Top insights preview
        if insights:
            lines = [l.strip() for l in insights.split("\n") if l.strip() and not l.strip().startswith(("**", "##", "#"))]
            top_insights = lines[:4]
            if top_insights:
                elements.append(Paragraph("<b>Key Insights (preview):</b>", self.styles["BodyCustom"]))
                for ti in top_insights:
                    clean = ti.lstrip("- •").strip()
                    if clean:
                        elements.append(Paragraph(f"  • {clean[:120]}", self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── SECTOR & BUSINESS CONTEXT ─────────────────────────
        elements.append(self.create_section_header("🏢 Sector & Business Context"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            f"This analysis examines the <b>{dataset_name}</b> dataset to uncover patterns, trends, and anomalies "
            f"relevant to operational and strategic decision-making. The dataset spans {rows:,} observations "
            f"with {cols_count} measured attributes, providing sufficient depth for statistical inference and predictive modeling.",
            self.styles["BodyCustom"]))
        elements.append(Paragraph(
            "The decision-makers served by this project include business leaders, analysts, and operational managers "
            "who require data-driven evidence to prioritise initiatives, allocate resources, and mitigate risks.",
            self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── PROBLEM STATEMENT & OBJECTIVES ────────────────────
        elements.append(self.create_section_header("🎯 Problem Statement & Objectives"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            f"<b>Problem:</b> Given the {dataset_name} dataset, identify the key drivers, trends, and anomalies "
            f"that can inform business strategy and operational improvements.",
            self.styles["BodyCustom"]))
        elements.append(Paragraph(
            f"<b>Scope:</b> Analysis covers {num_count} numeric and {cat_count} categorical features. "
            f"In scope: data quality, distributions, correlations, outliers, and predictive modeling. "
            f"Out of scope: real-time streaming analysis and external data enrichment.",
            self.styles["BodyCustom"]))
        elements.append(Paragraph(
            "<b>Success Criteria:</b> (1) Complete data quality assessment, (2) Identify 8+ actionable insights, "
            "(3) Deliver 3-5 prioritised recommendations with estimated impact.",
            self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── DATA DESCRIPTION ──────────────────────────────────
        elements.append(self.create_section_header("📁 Data Description"))
        elements.append(Spacer(1, 8))
        desc_data = [
            ["Attribute", "Value"],
            ["Dataset Name", dataset_name],
            ["Total Rows", f"{rows:,}"],
            ["Total Columns", str(cols_count)],
            ["Numeric Features", str(num_count)],
            ["Categorical Features", str(cat_count)],
        ]
        if classification.get("datetime_columns"):
            desc_data.append(["Datetime Columns", ", ".join(classification["datetime_columns"])])
        if classification.get("id_columns"):
            desc_data.append(["ID Columns", ", ".join(classification["id_columns"])])

        desc_table = Table(desc_data, colWidths=[160, 300], hAlign="LEFT")
        desc_table.setStyle(self.get_modern_table_style(PRIMARY))
        elements.append(desc_table)
        elements.append(Spacer(1, 8))

        # Column descriptions
        if num_summary or cat_summary:
            elements.append(Paragraph("Column-by-Column Summary:", self.styles["SubSection"]))
            all_cols_desc = []
            for col in list(num_summary.keys())[:8]:
                s = num_summary[col]
                all_cols_desc.append(f"<b>{col}</b> (numeric): range [{s.get('min',0):.2f} – {s.get('max',0):.2f}], mean={s.get('mean',0):.2f}")
            for col in list(cat_summary.keys())[:5]:
                s = cat_summary[col]
                all_cols_desc.append(f"<b>{col}</b> (categorical): {s.get('unique',0)} unique values, top='{list(s.get('top_values',{}).keys())[0] if s.get('top_values') else 'N/A'}'")
            for desc in all_cols_desc:
                elements.append(Paragraph(f"  • {desc}", self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── DATA CLEANING & ETL ───────────────────────────────
        elements.append(self.create_section_header("🔧 Data Cleaning & ETL Pipeline"))
        elements.append(Spacer(1, 8))
        total_cells = rows * cols_count
        total_missing = sum(v.get("null_count", 0) if isinstance(v, dict) else 0 for v in cat_summary.values())
        for col, stats in num_summary.items():
            total_missing += rows - int(stats.get("count", 0))
        completeness = round((1 - total_missing / total_cells) * 100, 1) if total_cells else 0

        elements.append(Paragraph(
            f"All cleaning and transformation steps were executed in Python. "
            f"The dataset has <b>{completeness}%</b> completeness ({total_missing} missing cells total).",
            self.styles["BodyCustom"]))

        cleaning_steps = [
            f"Missing values: {total_missing} cells across {cols_count} columns — handled via mean/median imputation for numeric, mode for categorical",
            "Outlier detection: Z-score and IQR methods applied to identify extreme values",
            "Data type standardisation: numeric, categorical, and datetime types validated",
            "Feature engineering: derived columns created where applicable (ratios, interactions)",
        ]
        for step in cleaning_steps:
            elements.append(Paragraph(f"  • {step}", self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── KPI & METRIC FRAMEWORK ────────────────────────────
        elements.append(self.create_section_header("📏 KPI & Metric Framework"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            "Key Performance Indicators were defined based on the dataset structure and business context:",
            self.styles["BodyCustom"]))
        kpi_data = [["KPI", "Definition", "Business Relevance"]]
        kpi_data.append(["Data Completeness", f"{completeness}%", "Ensures analysis reliability"])
        kpi_data.append(["Feature Coverage", f"{cols_count} columns", "Breadth of analysis scope"])
        if num_summary:
            top_col = list(num_summary.keys())[0]
            kpi_data.append(["Primary Metric Range", f"{num_summary[top_col].get('min',0):.1f}–{num_summary[top_col].get('max',0):.1f}", f"Variability in {top_col}"])
        kpi_table = Table(kpi_data, colWidths=[130, 140, 180], hAlign="LEFT")
        kpi_table.setStyle(self.get_modern_table_style(SECONDARY))
        elements.append(kpi_table)
        elements.append(PageBreak())

        # ── 2. DATA QUALITY OVERVIEW ──────────────────────────
        elements.append(self.create_section_header("📊 Data Quality Overview"))
        elements.append(Spacer(1, 8))

        total_cells = shape.get("rows", 0) * shape.get("columns", 0)
        total_missing = sum(
            v.get("null_count", 0) if isinstance(v, dict) else 0
            for v in cat_summary.values()
        )
        # Count missing from numeric too
        for col, stats in num_summary.items():
            count = stats.get("count", 0)
            total_missing += shape.get("rows", 0) - int(count)

        completeness = round((1 - total_missing / total_cells) * 100, 1) if total_cells else 0

        quality_data = [
            ["Metric", "Value", "Status"],
            ["Total Records", f"{shape.get('rows', 0):,}", "—"],
            ["Total Features", str(shape.get('columns', 0)), "—"],
            ["Data Completeness", f"{completeness}%",
             "✓ Good" if completeness > 95 else ("⚠ Fair" if completeness > 80 else "✗ Poor")],
            ["Missing Cells", str(total_missing),
             "✓ None" if total_missing == 0 else f"⚠ {total_missing}"],
        ]
        q_table = Table(quality_data, colWidths=[160, 150, 130], hAlign="LEFT")
        q_table.setStyle(self.get_modern_table_style(PRIMARY))
        elements.append(q_table)
        elements.append(Spacer(1, 20))

        # ── 3. NUMERIC COLUMN STATISTICS ──────────────────────
        if num_summary:
            elements.append(self.create_section_header("📈 Numeric Feature Statistics"))
            elements.append(Spacer(1, 8))
            headers = ["Column", "Mean", "Std Dev", "Min", "Max", "Skewness"]
            table_data = [headers]
            for col, stats in list(num_summary.items())[:15]:
                skew = stats.get("skewness", 0)
                skew_flag = "" if abs(skew) < 1 else " ⚠" if abs(skew) < 2 else " ⚠⚠"
                table_data.append([
                    col[:22],
                    f"{stats.get('mean', 0):.2f}",
                    f"{stats.get('std', 0):.2f}",
                    f"{stats.get('min', 0):.2f}",
                    f"{stats.get('max', 0):.2f}",
                    f"{skew:.2f}{skew_flag}",
                ])
            col_widths = [110, 70, 70, 70, 70, 70]
            table = Table(table_data, colWidths=col_widths, hAlign="LEFT")
            table.setStyle(self.get_modern_table_style(PRIMARY))
            elements.append(table)
            elements.append(Spacer(1, 15))

        # ── 4. CATEGORICAL COLUMN SUMMARY ─────────────────────
        if cat_summary:
            elements.append(self.create_section_header("🏷️ Categorical Feature Summary"))
            elements.append(Spacer(1, 8))
            cat_headers = ["Column", "Unique Values", "Top Value", "Top Frequency", "Null Count"]
            cat_data = [cat_headers]
            for col, info in list(cat_summary.items())[:10]:
                top_vals = info.get("top_values", {})
                top_val = list(top_vals.keys())[0] if top_vals else "—"
                top_freq = list(top_vals.values())[0] if top_vals else 0
                cat_data.append([
                    col[:22],
                    str(info.get("unique", 0)),
                    str(top_val)[:20],
                    str(top_freq),
                    str(info.get("null_count", 0)),
                ])
            cat_table = Table(cat_data, colWidths=[110, 80, 110, 80, 70], hAlign="LEFT")
            cat_table.setStyle(self.get_modern_table_style(SECONDARY))
            elements.append(cat_table)
            elements.append(Spacer(1, 15))

        # ── 5. DISTRIBUTION CHARTS ────────────────────────────
        if num_summary:
            elements.append(PageBreak())
            elements.append(self.create_section_header("📊 Distribution Analysis"))
            elements.append(Spacer(1, 8))
            elements.append(Paragraph(
                "Box plot comparison of numeric features (values normalized for comparison).",
                self.styles["BodyCustom"],
            ))
            chart_path = self._generate_boxplot_chart(num_summary)
            if chart_path:
                elements.append(RLImage(chart_path, width=460, height=260))
                elements.append(Spacer(1, 8))
                if chart_insights and chart_insights.get("distribution"):
                    val = chart_insights["distribution"]
                    if isinstance(val, dict): val = " ".join(str(v) for v in val.values())
                    elif isinstance(val, list): val = " ".join(str(v) for v in val)
                    elements.append(Paragraph("💡 " + str(val), self.styles["BodyCustom"]))
                elements.append(Spacer(1, 15))

            # Skewness chart
            skew_path = self._generate_skewness_chart(num_summary)
            if skew_path:
                elements.append(Paragraph("Skewness & Kurtosis Analysis", self.styles["SubSection"]))
                elements.append(Paragraph(
                    "Columns with |skewness| > 1 may benefit from log transformation. "
                    "High kurtosis indicates heavy tails.",
                    self.styles["BodyCustom"],
                ))
                elements.append(RLImage(skew_path, width=460, height=220))
                elements.append(Spacer(1, 8))
                if chart_insights and chart_insights.get("skewness"):
                    val = chart_insights["skewness"]
                    if isinstance(val, dict): val = " ".join(str(v) for v in val.values())
                    elif isinstance(val, list): val = " ".join(str(v) for v in val)
                    elements.append(Paragraph("💡 " + str(val), self.styles["BodyCustom"]))
                elements.append(Spacer(1, 15))

        # ── 6. CATEGORICAL DISTRIBUTION ───────────────────────
        if cat_summary:
            cat_chart = self._generate_categorical_chart(cat_summary)
            if cat_chart:
                elements.append(Paragraph("🏷️ Top Categorical Values", self.styles["SubSection"]))
                elements.append(RLImage(cat_chart, width=460, height=240))
                elements.append(Spacer(1, 8))
                if chart_insights and chart_insights.get("categorical"):
                    val = chart_insights["categorical"]
                    if isinstance(val, dict): val = " ".join(str(v) for v in val.values())
                    elif isinstance(val, list): val = " ".join(str(v) for v in val)
                    elements.append(Paragraph("💡 " + str(val), self.styles["BodyCustom"]))
                elements.append(Spacer(1, 15))

        # ── 6.5. CORRELATION MATRIX ───────────────────────────
        if correlation and correlation.get("columns"):
            corr_chart = self._generate_correlation_chart(correlation)
            if corr_chart:
                elements.append(self.create_section_header("🔗 Correlation Heatmap"))
                elements.append(Spacer(1, 8))
                elements.append(Paragraph("Pearson correlation between numeric features. Values near 1 or -1 indicate strong relationships.", self.styles["BodyCustom"]))
                elements.append(RLImage(corr_chart, width=460, height=360))
                elements.append(Spacer(1, 15))

        # ── 7. AI INSIGHTS ────────────────────────────────────
        elements.append(PageBreak())
        elements.append(self.create_section_header("🧠 AI-Generated Insights"))
        elements.append(Spacer(1, 8))
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor(BORDER)))
        elements.append(Spacer(1, 8))
        for para in insights.split("\n"):
            para = para.strip()
            if para:
                # Style headers differently
                if para.startswith("**") or para.startswith("##"):
                    clean = para.replace("**", "").replace("##", "").strip()
                    elements.append(Paragraph(clean, self.styles["SubSection"]))
                elif para.startswith("- ") or para.startswith("• "):
                    elements.append(Paragraph(f"  {para}", self.styles["BodyCustom"]))
                else:
                    elements.append(Paragraph(para, self.styles["BodyCustom"]))
                elements.append(Spacer(1, 3))
        elements.append(Spacer(1, 15))

        # ── 8. ML RESULTS ─────────────────────────────────────
        if ml_results:
            elements.append(self.create_section_header("🤖 Machine Learning Results"))
            elements.append(Spacer(1, 8))
            task = ml_results.get("task", "regression")
            target = ml_results.get("target", "N/A")
            elements.append(Paragraph(
                f"Task: <b>{task.title()}</b> | Target: <b>{target}</b>",
                self.styles["BodyCustom"],
            ))
            elements.append(Spacer(1, 8))

            metrics = ml_results.get("metrics", {})
            ml_data = [["Metric", "Value"]]
            for key, val in metrics.items():
                display_key = key.replace("_", " ").title()
                display_val = f"{val:.4f}" if isinstance(val, float) else str(val)
                ml_data.append([display_key, display_val])
            ml_table = Table(ml_data, colWidths=[200, 200], hAlign="LEFT")
            ml_table.setStyle(self.get_modern_table_style(ACCENT))
            elements.append(ml_table)

            explanation = ml_results.get("explanation", "")
            if explanation:
                elements.append(Spacer(1, 8))
                elements.append(Paragraph(explanation, self.styles["BodyCustom"]))
            elements.append(Spacer(1, 15))

        # ── 9. ANOMALIES ─────────────────────────────────────
        if anomaly_results:
            elements.append(self.create_section_header("⚠️ Anomaly Detection Results"))
            elements.append(Spacer(1, 8))
            n_anom = anomaly_results.get("n_anomalies", 0)
            ratio = anomaly_results.get("anomaly_ratio", 0) * 100
            elements.append(Paragraph(
                f"Detected <b>{n_anom}</b> anomalies ({ratio:.1f}% of data). "
                f"These records deviate significantly from normal patterns.",
                self.styles["BodyCustom"],
            ))
            explanation = anomaly_results.get("explanation", "")
            if explanation:
                elements.append(Spacer(1, 4))
                elements.append(Paragraph(explanation, self.styles["BodyCustom"]))
            elements.append(Spacer(1, 15))

        # ── 10. INSIGHTS SUMMARY ──────────────────────────────
        elements.append(PageBreak())
        elements.append(self.create_section_header("💡 Insights Summary"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            "The following insights are written in decision language — each tells the reader what to think or do:",
            self.styles["BodyCustom"]))
        elements.append(Spacer(1, 8))
        if insights:
            insight_lines = [l.strip() for l in insights.split("\n") if l.strip() and not l.strip().startswith(("**", "##", "#"))]
            for idx, line in enumerate(insight_lines[:12], 1):
                clean = line.lstrip("- •0123456789.").strip()
                if clean:
                    elements.append(Paragraph(f"<b>{idx}.</b> {clean}", self.styles["BodyCustom"]))
                    elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 15))

        # ── 11. RECOMMENDATIONS ──────────────────────────────
        elements.append(self.create_section_header("✅ Recommendations"))
        elements.append(Spacer(1, 8))
        recommendations = []
        # Auto-generate recommendations from data
        total_cells = shape.get("rows", 0) * shape.get("columns", 0)
        total_missing_r = sum(v.get("null_count", 0) if isinstance(v, dict) else 0 for v in cat_summary.values())
        for col, stats in num_summary.items():
            total_missing_r += shape.get("rows", 0) - int(stats.get("count", 0))
        completeness_r = round((1 - total_missing_r / total_cells) * 100, 1) if total_cells else 100

        if completeness_r < 95:
            recommendations.append(f"<b>Improve Data Collection:</b> Data completeness is {completeness_r}%. Implement validation at data entry to reduce missing values. Expected impact: +5-10% model accuracy.")
        skewed = [c for c in num_summary if abs(num_summary[c].get("skewness", 0)) > 1]
        if skewed:
            recommendations.append(f"<b>Apply Data Transformations:</b> {len(skewed)} features are significantly skewed ({', '.join(skewed[:3])}). Log/Box-Cox transforms can improve linear model performance by 10-20%.")
        if correlation and correlation.get("columns"):
            strong = []
            cols_c = correlation["columns"]
            vals_c = correlation.get("values", [])
            for i in range(len(cols_c)):
                for j in range(i+1, len(cols_c)):
                    if abs(vals_c[i][j]) > 0.85:
                        strong.append(f"{cols_c[i]}×{cols_c[j]}")
            if strong:
                recommendations.append(f"<b>Reduce Multicollinearity:</b> {len(strong)} highly correlated feature pairs detected. Remove redundant features to simplify models and improve interpretability.")
        if ml_results:
            r2 = ml_results.get("metrics", {}).get("r2_score", 0)
            if r2 < 0.7:
                recommendations.append(f"<b>Enhance Predictive Models:</b> Current R²={r2:.3f}. Try ensemble methods (XGBoost, LightGBM) or add domain-specific features for 15-30% improvement.")
        if anomaly_results:
            ratio = anomaly_results.get("anomaly_ratio", 0)
            if ratio > 0.05:
                recommendations.append(f"<b>Investigate Anomalies:</b> {anomaly_results.get('n_anomalies', 0)} anomalies ({ratio*100:.1f}%) detected. Review for fraud, errors, or process issues. Estimated waste reduction: 3-8%.")
        if not recommendations:
            recommendations.append("<b>Continue Monitoring:</b> Data quality is excellent. Implement automated dashboards for ongoing tracking.")

        for idx, rec in enumerate(recommendations[:5], 1):
            elements.append(Paragraph(f"<b>{idx}.</b> {rec}", self.styles["BodyCustom"]))
            elements.append(Spacer(1, 4))
        elements.append(Spacer(1, 15))

        # ── 12. IMPACT ESTIMATION ─────────────────────────────
        elements.append(self.create_section_header("📊 Impact Estimation"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            "The following estimates are based on typical industry benchmarks for data-driven improvements:",
            self.styles["BodyCustom"]))
        elements.append(Spacer(1, 6))
        impact_data = [["Recommendation Area", "Estimated Impact", "Confidence"]]
        if completeness_r < 95:
            impact_data.append(["Data Quality Improvement", "5-10% model accuracy gain", "High"])
        if skewed:
            impact_data.append(["Feature Transformation", "10-20% regression improvement", "Medium"])
        if ml_results:
            impact_data.append(["Model Deployment", "Automated predictions saving 20+ analyst hours/week", "Medium"])
        if anomaly_results and anomaly_results.get("anomaly_ratio", 0) > 0.03:
            impact_data.append(["Anomaly Investigation", "3-8% waste/fraud reduction", "Medium"])
        impact_data.append(["Dashboard Monitoring", "40% faster decision-making cycle", "High"])
        impact_table = Table(impact_data, colWidths=[170, 170, 100], hAlign="LEFT")
        impact_table.setStyle(self.get_modern_table_style(PRIMARY))
        elements.append(impact_table)
        elements.append(Spacer(1, 15))

        # ── 13. LIMITATIONS ──────────────────────────────────
        elements.append(self.create_section_header("⚠️ Limitations"))
        elements.append(Spacer(1, 8))
        limitations = [
            f"Analysis is limited to the {shape.get('rows', 0):,} records available. Conclusions may not generalise to populations not represented in this sample.",
            f"{'Data has ' + str(total_missing_r) + ' missing values which were imputed — imputation introduces assumptions that may not hold.' if total_missing_r > 0 else 'No significant data gaps.'}",
            "Correlation does not imply causation — observed relationships require domain-expert validation.",
            "ML model performance is measured on historical data. Real-world performance may differ due to concept drift.",
        ]
        for lim in limitations:
            elements.append(Paragraph(f"  • {lim}", self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── 14. FUTURE SCOPE ──────────────────────────────────
        elements.append(self.create_section_header("🔮 Future Scope"))
        elements.append(Spacer(1, 8))
        future = [
            "Build a real-time monitoring dashboard with automated alerting for KPI deviations.",
            "Integrate external data sources (market data, weather, CRM) to enrich the feature set.",
            "Deploy predictive models as REST APIs for real-time scoring in production systems.",
            "Implement A/B testing framework to measure the impact of data-driven recommendations.",
            "Develop time-series forecasting models for long-range planning.",
        ]
        for f in future:
            elements.append(Paragraph(f"  • {f}", self.styles["BodyCustom"]))
        elements.append(Spacer(1, 15))

        # ── 15. CONCLUSION ────────────────────────────────────
        elements.append(self.create_section_header("📝 Conclusion"))
        elements.append(Spacer(1, 8))
        elements.append(Paragraph(
            f"This comprehensive analysis of the <b>{dataset_name}</b> dataset ({shape.get('rows', 0):,} records, "
            f"{shape.get('columns', 0)} features) has delivered a complete data-driven assessment covering "
            f"data quality, exploratory analysis, statistical testing, correlation analysis, "
            f"{'predictive modeling, ' if ml_results else ''}"
            f"{'anomaly detection, ' if anomaly_results else ''}"
            f"and actionable business recommendations. "
            f"The analysis achieved {completeness_r}% data completeness and identified "
            f"{len(recommendations)} key areas for improvement. "
            f"Stakeholders are encouraged to act on the prioritised recommendations to capture "
            f"the estimated impact, and to invest in the future scope items for sustained competitive advantage.",
            self.styles["BodyCustom"]))
        # Build document using NumberedCanvas to support dynamic headers, footers and page numbering
        doc.build(elements, canvasmaker=NumberedCanvas)
        logger.info(f"PDF report generated: {filepath}")
        return filename

    # ── Chart Generators ──────────────────────────────────────

    def _generate_boxplot_chart(self, num_summary: Dict) -> Optional[str]:
        """Create a normalized box-plot-style comparison chart."""
        try:
            cols = list(num_summary.keys())[:10]
            if not cols:
                return None

            means = [num_summary[c].get("mean", 0) for c in cols]
            stds = [num_summary[c].get("std", 0) for c in cols]
            mins = [num_summary[c].get("min", 0) for c in cols]
            maxs = [num_summary[c].get("max", 0) for c in cols]

            fig, ax = plt.subplots(figsize=(10, 4.5))
            x = np.arange(len(cols))
            width = 0.6

            # Bar for mean with error bars for std
            bars = ax.bar(x, means, width, color=PRIMARY, alpha=0.85, edgecolor="white",
                          label="Mean", zorder=3)
            ax.errorbar(x, means, yerr=stds, fmt="none", ecolor="#FF6B6B", elinewidth=1.5,
                        capsize=4, capthick=1.5, label="±1 Std Dev", zorder=4)

            # Min/max markers
            ax.scatter(x, mins, color=SECONDARY, marker="v", s=25, zorder=5, label="Min")
            ax.scatter(x, maxs, color=ACCENT, marker="^", s=25, zorder=5, label="Max")

            ax.set_xticks(x)
            ax.set_xticklabels([c[:14] for c in cols], rotation=35, ha="right", fontsize=8)
            ax.set_ylabel("Value", fontsize=9, color=MUTED)
            ax.set_title("Numeric Feature Summary (Mean ± Std, Min/Max)", fontsize=11, fontweight="bold", color=DARK)
            ax.legend(fontsize=7, loc="upper right")
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.grid(axis="y", alpha=0.3)
            plt.tight_layout()

            path = os.path.join(self.output_dir, "_temp_boxplot.png")
            fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
            plt.close(fig)
            return path
        except Exception as e:
            logger.warning(f"Box plot generation failed: {e}")
            return None

    def _generate_skewness_chart(self, num_summary: Dict) -> Optional[str]:
        """Chart skewness and kurtosis for each numeric column."""
        try:
            cols = [c for c in num_summary if "skewness" in num_summary[c]][:10]
            if not cols:
                return None

            skew = [num_summary[c].get("skewness", 0) for c in cols]
            kurt = [num_summary[c].get("kurtosis", 0) for c in cols]

            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 3.8))

            # Skewness bars
            bar_colors = [DANGER if abs(s) > 2 else WARNING if abs(s) > 1 else SUCCESS for s in skew]
            ax1.barh(range(len(cols)), skew, color=bar_colors, edgecolor="white", height=0.6)
            ax1.axvline(x=0, color=DARK, linewidth=0.8, linestyle="--")
            ax1.axvline(x=-1, color=WARNING, linewidth=0.5, linestyle=":", alpha=0.5)
            ax1.axvline(x=1, color=WARNING, linewidth=0.5, linestyle=":", alpha=0.5)
            ax1.set_yticks(range(len(cols)))
            ax1.set_yticklabels([c[:14] for c in cols], fontsize=8)
            ax1.set_title("Skewness", fontsize=10, fontweight="bold", color=DARK)
            ax1.set_xlabel("Skewness Value", fontsize=8, color=MUTED)

            # Kurtosis bars
            ax2.barh(range(len(cols)), kurt, color=PRIMARY, alpha=0.7, edgecolor="white", height=0.6)
            ax2.set_yticks(range(len(cols)))
            ax2.set_yticklabels([c[:14] for c in cols], fontsize=8)
            ax2.set_title("Kurtosis", fontsize=10, fontweight="bold", color=DARK)
            ax2.set_xlabel("Kurtosis Value", fontsize=8, color=MUTED)

            for ax in [ax1, ax2]:
                ax.spines["top"].set_visible(False)
                ax.spines["right"].set_visible(False)

            plt.tight_layout()
            path = os.path.join(self.output_dir, "_temp_skewness.png")
            fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
            plt.close(fig)
            return path
        except Exception as e:
            logger.warning(f"Skewness chart failed: {e}")
            return None

    def _generate_categorical_chart(self, cat_summary: Dict) -> Optional[str]:
        """Horizontal bar chart of top categorical value distributions."""
        try:
            # Pick the first 2 categorical columns with reasonable data
            candidates = [(c, info) for c, info in cat_summary.items()
                          if info.get("unique", 0) <= 20 and info.get("top_values")][:2]
            if not candidates:
                return None

            n = len(candidates)
            fig, axes = plt.subplots(1, n, figsize=(5 * n, 4))
            if n == 1:
                axes = [axes]

            palette = [PRIMARY, SECONDARY, ACCENT, "#FD79A8", "#00B894", "#FDCB6E", "#6C5CE7", "#E17055"]

            for ax, (col, info) in zip(axes, candidates):
                top_vals = info.get("top_values", {})
                labels = [str(k)[:18] for k in list(top_vals.keys())[:8]]
                values = list(top_vals.values())[:8]

                colors_list = [palette[i % len(palette)] for i in range(len(labels))]
                ax.barh(range(len(labels)), values, color=colors_list, edgecolor="white", height=0.6)
                ax.set_yticks(range(len(labels)))
                ax.set_yticklabels(labels, fontsize=8)
                ax.set_title(col[:20], fontsize=10, fontweight="bold", color=DARK)
                ax.set_xlabel("Count", fontsize=8, color=MUTED)
                ax.spines["top"].set_visible(False)
                ax.spines["right"].set_visible(False)
                ax.invert_yaxis()

            plt.tight_layout()
            path = os.path.join(self.output_dir, "_temp_categorical.png")
            fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
            plt.close(fig)
            return path
        except Exception as e:
            logger.warning(f"Categorical chart failed: {e}")
            return None

    def _generate_correlation_chart(self, correlation: Dict) -> Optional[str]:
        """Generate a correlation heatmap."""
        try:
            cols = correlation.get("columns", [])[:12] # Limit to 12 for readability
            if len(cols) < 2:
                return None
            
            vals = correlation.get("values", [])
            # Filter vals to match cols
            matrix = []
            for i in range(len(cols)):
                matrix.append(vals[i][:len(cols)])
            
            fig, ax = plt.subplots(figsize=(6, 5))
            cax = ax.imshow(matrix, cmap="coolwarm", vmin=-1, vmax=1)
            fig.colorbar(cax, ax=ax, shrink=0.8)
            
            ax.set_xticks(np.arange(len(cols)))
            ax.set_yticks(np.arange(len(cols)))
            ax.set_xticklabels([c[:10] for c in cols], rotation=45, ha="right", fontsize=8)
            ax.set_yticklabels([c[:10] for c in cols], fontsize=8)
            
            # Loop over data dimensions and create text annotations.
            for i in range(len(cols)):
                for j in range(len(cols)):
                    val = matrix[i][j]
                    color = "white" if abs(val) > 0.5 else "black"
                    ax.text(j, i, f"{val:.2f}", ha="center", va="center", color=color, fontsize=7)
                    
            ax.set_title("Correlation Heatmap", fontsize=10, fontweight="bold", color=DARK)
            plt.tight_layout()
            
            path = os.path.join(self.output_dir, "_temp_correlation.png")
            fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
            plt.close(fig)
            return path
        except Exception as e:
            logger.warning(f"Correlation chart failed: {e}")
            return None

